language: python
python:
  - "3.6"
sudo: required

before_install: true
install:
  - pip install -r requirements/dev.txt

script:
  - pylint --output-format=text app.py
  - python -m unittest discover